services:

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - static_volume:/app/admin_static/admin

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static/admin/
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - backend

volumes:
  static_volume:
