services:

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - static_volume:/app/backend_static/static/admin

  nginx:
    image: nginx
    container_name: foodgram-nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static/admin-static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - backend

volumes:
  static_volume:
